### ISSUE TITLE
Calendar created pages are not journal pages

### ISSUE THREAD

**Issue by ianmcn** [logseq/logseq-plugin-samples#15]
Calendar created pages are not the same as the journal pages, despite having the same titles. See gif for demo. Plugin and Logseq are on the latest.
![logseq](https://user-images.githubusercontent.com/2265103/140506886-5e2c0d37-cba3-428b-97c1-2d814f80e3be.gif)

**Comment by scottrblock** [comment]
the `logseq-reddit-hot-news` sample also creates links this way, so i did the same in developing my plugin. is there a different way to link to journal pages or is this a logseq bug?

**Comment by ianmcn** [comment]
I think it was a logseq bug. It used to work fine, then it broke (as per my post) and stayed broken for a few versions, but now it's working for me again. Thanks for the great plugin!
