### ISSUE TITLE
Is there any plan to publish pomodoro plugin to the store?

### ISSUE THREAD

**Issue by futantan** [logseq/logseq-plugin-samples#22]
The pomodoro timer looks great, is there any plan to publish this? I didn't find it in the store.

**Comment by xyhp915** [comment]
There's a marketplace plugin [#PR](https://github.com/logseq/marketplace/pull/48) for it. But it is still pending ...

**Comment by futantan** [comment]
Thank you @xyhp915 for letting me know!
