### ISSUE TITLE
Journals Calendar change first day to Monday

### ISSUE THREAD

**Issue by santiyounger** [logseq/logseq-plugin-samples#23]
hey, I love this plugin, would be interested to learn how to change the first day to monday. I opened the file `logseq-journals-calendar.json` but since it's an empty file I couldn't figure out if there's an existing way to change the first day of the week

![image](https://user-images.githubusercontent.com/51902730/163242411-339ecd6a-d8b1-41ec-bb72-b888a67f640d.png)

Let me know if it there's an existing way, if not this would be a great feature for those of use that prefer monday as the first day of the week

Thanks a lot!

**Comment by xyhp915** [comment]
Hi @santiyounger I enhanced this feature of `logseq-journals-calendar` plugin from marketplace. You can reinstall it or upgrade to 0.10.2 (https://github.com/xyhp915/logseq-journals-calendar). After that, open settings json file to do this configures as below ⬇️ 

```json
{
  "props": {
      "first-day-of-week": 2,
      "color": "pink"
  }
}
```
Valid props -> https://vcalendar.io/api/v2.0/calendar.html#props

Then, reload app or off/on plugin to activate settings.


### It works now?
<img width="304" alt="CleanShot 2022-04-14 at 13 57 40@2x" src="https://user-images.githubusercontent.com/1779837/163322980-d3ddbd45-105d-4902-80ab-47b2c9ec0d92.png">

**Comment by santiyounger** [comment]
@xyhp915 thanks a lot for your solution. I seemed to have lost track of this issue, my bad

I just updated the plugin, and was very happy to see the new setting for first day

![image](https://user-images.githubusercontent.com/51902730/180100586-ec092991-f990-459f-8916-1a32c251ff61.png)

It worked great, thank you so much!
